### PR TITLE
Allow users to change cache dir for bloop

### PR DESCRIPTION
**Pull request by lwronski**

### CODE REVIEW

**Comment by tgodzik** [comment]
What is this needed for? Maybe it's worth upstreaming?

**Comment by lwronski** [comment]
> What is this needed for? Maybe it's worth upstreaming?

I want to enable changing cache directory for bloop, to download all necessary dependencies and cache them. Because I want to allow users to run scala-cli without access to internet, so I need all required dependencies downloaded for bloop.

**Comment by tgodzik** [comment]
> > What is this needed for? Maybe it's worth upstreaming?
> 
> I want to enable changing cache directory for bloop, to download all necessary dependencies and cache them. Because I want to allow users to run scala-cli without access to internet, so I need all required dependencies downloaded for bloop.

Wouldn't eat be easier to just download it to the default directory instead of adding the new config option?

**Comment by alexarchambault** [comment]
> Wouldn't eat be easier to just download it to the default directory instead of adding the new config option?

@tgodzik My understanding is that @lwronski uses that option only under special circumstances. We should have a command in Scala CLI allowing to generate an archive with all required JARs pre-fetched. Tweaking the Bloop cache location allows to know which JARs Bloop downloads in scenarios we want the archive to support.

**Comment by alexarchambault** [comment]
It might be worth upstreaming it, yeah.

**Comment by tgodzik** [comment]
We started discussing it with @lwronski and maybe we should have just one command:
`scala-cli cache . -S 3.1.0` which would create a cache in a stable location like `.cache/.bleep/bleep-3.1.0.zip` and then we would find it automatically if it exists and unpack to the default location?

But on the other hand, if we would do that when creating a VM, why not just run the compilation itself to cache its results? This would skip the additional steps of having to manually send a zip somewhere and use it.

**Comment by lwronski** [comment]
I will close this PR as we currently have no plans to create scala-cli caches. There are numerous security concerns that need to be analyse.

**Pull request closed without merging**
