### PR TITLE
Updated js-bridge with newest configuration

### PR DESCRIPTION
**Pull request by KristianAN**

### CODE REVIEW

**Comment by KristianAN** [comment]
I had some trouble getting tests to run for this on my system and in CI with diffirent errors that didn't really make sense considering the changes in the PR, so it would be nice to see them run on CI here so I can actually know if I've broken anything or it's just some strange behavior I need to take a look at.

**Comment by tgodzik** [comment]
Looks to be working. Would you mind contributing this to scalacenter/bloop ? I am already working around merging this fork to the main Bloop

**Comment by KristianAN** [comment]
Yes, I'll PR this in scalacenter/bloop asap.

**Comment by tgodzik** [comment]
No need for ASAP :sweat_smile:

**Comment by KristianAN** [comment]
@tgodzik So, could not fork the original when I had a fork of a fork, so when I removed the fork apparently this PR is closed?

Anyway... https://github.com/scalacenter/bloop/pull/2359

**Pull request closed without merging**
